# Generated by Django 5.1.3 on 2024-11-21 14:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False, 
                    verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(
                    choices=[('Sedan', 'Sedan'),
                             ('SUV', 'SUV'),
                             ('Wagon', 'Wagon')],
                    max_length=10)),
                ('year', models.DateField(
                    default=datetime.date.today)),
                ('car_make', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='djangoapp.carmake')),
            ],
        ),
    ]
